### PR TITLE
make viz result more understandable

### PR DESCRIPTION
**Pull request by Kotomi-Du**

### CODE REVIEW

**Review by YanjiePa — COMMENTED** [review]
In my opinion, class name Point could not reflect what it aims for. I suggest rename the class from Point to Visualization, and then rename the visualization function to draw_figure().

**Review by xrhintelacc — APPROVED** [review]

**Comment by Kotomi-Du** [comment]
> In my opinion, class name Point could not reflect what it aims for. I suggest rename the class from Point to Visualization, and then rename the visualization function to draw_figure().

@YanjiePa  This `Point` is not a class for visualization, just to describe a location(x,y) which used for the definition of different position. Also changing `visualization()` function to other name is a good idea and `draw_statistics()` may be another good choice

**Comment by YanjiePa** [comment]
> > In my opinion, class name Point could not reflect what it aims for. I suggest rename the class from Point to Visualization, and then rename the visualization function to draw_figure().
> 
> @YanjiePa This `Point` is not a class for visualization, just to describe a location(x,y) which used for the definition of different position. Also changing `visualization()` function to other name is a good idea and `draw_statistics()` may be another good choice

@Kotomi-Du Oh, then I misunderstand the class Point. How about draw_decision_statistics()?

**Comment by Kotomi-Du** [comment]
> > > In my opinion, class name Point could not reflect what it aims for. I suggest rename the class from Point to Visualization, and then rename the visualization function to draw_figure().
> > 
> > 
> > @YanjiePa This `Point` is not a class for visualization, just to describe a location(x,y) which used for the definition of different position. Also changing `visualization()` function to other name is a good idea and `draw_statistics()` may be another good choice
> 
> @Kotomi-Du Oh, then I misunderstand the class Point. How about draw_decision_statistics()?

@YanjiePa  Perfect

**Pull request merged**
